seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefox:
  image: selenium/node-firefox
  ports:
    - 5900
  links:
    - seleniumhub:hub

chrome:
  image: selenium/node-chrome
  ports:
    - 5900
  links:
    - seleniumhub:hub
    